services:
  - type: web
    name: courseapp
    env: java
    envVars:
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-21-openjdk-amd64
    buildCommand: |
      echo "JAVA_HOME is set to: $JAVA_HOME"
      java -version
      ./mvnw clean install
    startCommand: ./mvnw spring-boot:run
