services:
  - type: web
    name: CourseDemoApp
    env: java
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/yourapp.jar
    envVars:
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-11-openjdk-amd64
