services:
  - type: web
    name: CourseDemoApp
    env: java
    branch: master
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/demo-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase: false
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase: false
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase: false
