services:
  - type: web
    name: CourseDemoApp
    env: java
    branch: master
    buildCommand: cd courseapp/demoo/demo && ./mvnw clean install
    startCommand: java -jar courseapp/demoo/demo/target/demo-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
      - key: SPRING_DATASOURCE_USERNAME
      - key: SPRING_DATASOURCE_PASSWORD
