services:
  - type: web
    name: courseapp
    env: java
    buildCommand: "./mvnw clean install"
    startCommand: ./mvnw spring-boot:run
    envVars:
      - key: JAVA_HOME
        value: /opt/render/project/.render_home/java
