services:
  - type: web
    name: courseapp
    env: java
    envVars:
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-21-openjdk-amd64
    buildCommand: ./mvnw clean install
    startCommand: ./mvnw spring-boot:run
