services:
  - type: web
    name: courseapp
    env: java
    buildCommand: "./mvnw clean install"
    startCommand: "java -jar target/demo-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: JAVA_HOME
        value: /opt/render/project/.render_home/java
