services:
  - type: web
    name: courseapp
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromEnvironment: true
      - key: SPRING_DATASOURCE_USERNAME
        fromEnvironment: true
      - key: SPRING_DATASOURCE_PASSWORD
        fromEnvironment: true
      - key: COMMERCETOOLS_PROJECTKEY
        fromEnvironment: true
      - key: COMMERCETOOLS_CLIENTID
        fromEnvironment: true
      - key: COMMERCETOOLS_CLIENTSECRET
        fromEnvironment: true
